name: Windows11_24H2_amd64
on: workflow_dispatch
jobs:
  Windows11_24H2_amd64:
    runs-on: windows-latest
    env:
      Build_VERSION: '26100.8313'
      FILE_NAME: Windows11_24H2_amd64
      UUP_DIR: Windows11_24H2_amd64
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Build ISO
      shell: cmd
      run: 'cd "${{ env.UUP_DIR }}"

        uup_download_windows.cmd'
    - name: Package
      run: 7z a -v1950m "${{ env.FILE_NAME }}-${{ env.Build_VERSION }}.7z" "./${{ env.UUP_DIR }}/*.iso" -mx=0
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.FILE_NAME }}-${{ env.Build_VERSION }}
        files: ${{ env.FILE_NAME }}-${{ env.Build_VERSION }}.7z*
